### ISSUE TITLE
[bug] Didn't receive any mail

### ISSUE THREAD

**Issue by Jakob-Bach** [bendixsonnenberg/CS-Select#85]
Tried the invitation function during game creation and on the overview, but did not receive any mail.

**Comment by Weitspringer** [comment]
What Email did you put in. Were there no typos?

**Comment by SeineEloquenz** [comment]
I'm getting invitation as well as reset mails, is this still a problem on someone elses end?

**Comment by Jakob-Bach** [comment]
I'm putting in my own KIT mail address. Plus, the join issue (#154) does not seem to be resolved (tested with current version of `master`, stack traces shortened by me):

```
ERROR: org.apache.commons.mail.EmailException: Sending the email to the following server failed : mail.gmx.net:465
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1401)
	at org.apache.commons.mail.Email.send(Email.java:1428)
	at com.csselect.email.EmailSender.sendEmail(EmailSender.java:42)
	at com.csselect.game.gamecreation.GameCreator.doCreate(GameCreator.java:119)
	...
Caused by: javax.mail.MessagingException: Could not connect to SMTP host: mail.gmx.net, port: 465
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1282)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:370)
	...
2019-02-12 07:52:29 [http-nio-8080-exec-5] com.csselect.email.EmailSender.sendEmail()
ERROR: org.apache.commons.mail.EmailException: javax.mail.internet.AddressException: Illegal character in domain in string ``jakob.bach@kit.edu_jakob.bach@kit.edu''
	at org.apache.commons.mail.Email.createInternetAddress(Email.java:1870)
	at org.apache.commons.mail.Email.addTo(Email.java:833)
	at org.apache.commons.mail.Email.addTo(Email.java:816)
	at org.apache.commons.mail.Email.addTo(Email.java:765)
	at com.csselect.email.EmailSender.sendEmail(EmailSender.java:41)
	at com.csselect.game.gamecreation.GameCreator.doCreate(GameCreator.java:119)
	...
Caused by: javax.mail.internet.AddressException: Illegal character in domain
	at javax.mail.internet.InternetAddress.checkAddress(InternetAddress.java:933)
	at javax.mail.internet.InternetAddress.parse(InternetAddress.java:819)
	at javax.mail.internet.InternetAddress.parse(InternetAddress.java:555)
	at javax.mail.internet.InternetAddress.<init>(InternetAddress.java:91)
	at org.apache.commons.mail.Email.createInternetAddress(Email.java:1845)
	...
```

The exactly same error (showing the same mail address!) appears even if I invite different mail addresses.

**Comment by Jakob-Bach** [comment]
Ok, ATIS is blocking port 465 if I'm connected via LAN. I needed to switch to KIT WLAN. 💩
